import os
import pickle
import pandas as pd

class CreditModelEngine:
    def __init__(self):
        self.model = None
        self.explainer = None
        self.is_loaded = False

    def load_models(self):
        # We assume the models were generated by the data_generator and train.py scripts in the /model/ dir.
        # In a real environment, this path would be configured or models downloaded from a registry.
        model_dir = os.path.join(os.path.dirname(__file__), "..", "..", "..", "model", "saved_models")
        model_path = os.path.join(model_dir, "xgboost_credit_model.pkl")
        explainer_path = os.path.join(model_dir, "shap_explainer.pkl")
        
        if os.path.exists(model_path) and os.path.exists(explainer_path):
            with open(model_path, "rb") as f:
                self.model = pickle.load(f)
            with open(explainer_path, "rb") as f:
                self.explainer = pickle.load(f)
            self.is_loaded = True
            print("Successfully loaded XGBoost and SHAP models into memory.")
        else:
            print(f"WARNING: Models not found at {model_dir}. Please run the training script.")

    def predict(self, profile_data: dict):
        if not self.is_loaded:
            raise RuntimeError("Model is not loaded.")
            
        # Ensure the feature order matches the training script
        features = ['monthly_income', 'monthly_expenses', 'savings_balance', 'missed_utility_bills', 'transaction_frequency']
        df = pd.DataFrame([{f: profile_data.get(f, 0) for f in features}])
        
        # Inference
        score = self.model.predict(df)[0]
        
        # Explainability
        shap_values = self.explainer.shap_values(df)
        shap_dict = {feat: float(val) for feat, val in zip(features, shap_values[0])}
        
        # Compute Risk Level based on score
        if score < 580:
            risk = "High"
        elif score < 670:
            risk = "Medium"
        else:
            risk = "Low"
            
        return {
            "credit_score": int(score),
            "risk_level": risk,
            "confidence_score": 0.85, # placeholder for probability confidence
            "shap_values": shap_dict
        }

# Global singleton
ml_engine = CreditModelEngine()
